# Site settings
title: 크림슈가도넛의 Github Pages
email: lks21c@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lks21c.gitub.io" # the base hostname & protocol for your site
twitter_username: lks21c
github_username: lks21c 

# Build settings
markdown: kramdown
